// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapWkeHAgSfy24cyVLW0YuIDOqmyCm_rA',
    appId: '1:368440218105:android:98b9933987c64c580d2d28',
    messagingSenderId: '368440218105',
    projectId: 'fir-pharmeasy',
    storageBucket: 'fir-pharmeasy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oaEi_xkPwpXioHnMkyppzy30UCOyGH4',
    appId: '1:368440218105:ios:2f6922b91b47bd330d2d28',
    messagingSenderId: '368440218105',
    projectId: 'fir-pharmeasy',
    storageBucket: 'fir-pharmeasy.appspot.com',
    iosClientId: '368440218105-20ki46kspmsnc3bkg355dtkngpjjbeng.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmeasy',
  );
}
